swagger: "2.0"
info:
  title: "Image Test PoC"
  description: '<img src="https://certifica.buengobierno.gob.mx/html/images/BG_logo.png/?text=XSS+EJECUTADO" style="border:3px solid red;display:block;margin:10px;">'
  version: "1.0.0"
paths: {}
